apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: node-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cars-node
subjects:
- kind: ServiceAccount
  name: cars-node
  namespace: system
