apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: cars-node
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - deployments
  - configmaps
  - secrets
  - endpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - update
  - create
  - list
  - watch

